# Generated by Django 5.2.8 on 2025-12-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва кімнати')),
                ('capacity', models.IntegerField(verbose_name='Вмістимість')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за годину')),
                ('features', models.TextField(blank=True, verbose_name='Особливості')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Початок')),
                ('end_time', models.DateTimeField(verbose_name='Кінець')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.room', verbose_name='Кімната')),
            ],
        ),
    ]
