# Generated by assistant — adds latitude/longitude to Room
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
    ]
